import { UnitDefinition, UnitId, CategoryType } from './schema'

export const CATEGORIES: CategoryType[] = [
  'length',
  'mass',
  'volume',
  'temperature',
  'digital_data',
  'time',
]

export const CATEGORY_LABELS: Record<CategoryType, string> = {
  length: 'Длина',
  mass: 'Вес и Масса',
  volume: 'Объем',
  temperature: 'Температура',
  digital_data: 'Данные',
  time: 'Время',
}

export const UNITS_DATA: Record<UnitId, UnitDefinition> = {
  // --- ДЛИНА (Базовая единица: метр) ---
  millimeter: {
    id: 'millimeter',
    label: 'Миллиметр',
    shortLabel: 'мм',
    category: 'length',
    system: 'metric',
    multiplier: 0.001,
    offset: 0,
  },
  centimeter: {
    id: 'centimeter',
    label: 'Сантиметр',
    shortLabel: 'см',
    category: 'length',
    system: 'metric',
    multiplier: 0.01,
    offset: 0,
  },
  meter: {
    id: 'meter',
    label: 'Метр',
    shortLabel: 'м',
    category: 'length',
    system: 'metric',
    multiplier: 1,
    offset: 0,
  },
  kilometer: {
    id: 'kilometer',
    label: 'Километр',
    shortLabel: 'км',
    category: 'length',
    system: 'metric',
    multiplier: 1000,
    offset: 0,
  },
  inch: {
    id: 'inch',
    label: 'Дюйм',
    shortLabel: 'in',
    category: 'length',
    system: 'imperial',
    multiplier: 0.0254,
    offset: 0,
  },
  foot: {
    id: 'foot',
    label: 'Футы',
    shortLabel: 'ft',
    category: 'length',
    system: 'imperial',
    multiplier: 0.3048,
    offset: 0,
  },
  yard: {
    id: 'yard',
    label: 'Ярд',
    shortLabel: 'yd',
    category: 'length',
    system: 'imperial',
    multiplier: 0.9144,
    offset: 0,
  },
  mile: {
    id: 'mile',
    label: 'Миля',
    shortLabel: 'mi',
    category: 'length',
    system: 'imperial',
    multiplier: 1609.34,
    offset: 0,
  },
  nautical_mile: {
    id: 'nautical_mile',
    label: 'Морская миля',
    shortLabel: 'nmi',
    category: 'length',
    system: 'imperial',
    multiplier: 1852,
    offset: 0,
  },

  // --- ВЕС / МАССА (Базовая единица: килограмм) ---
  milligram: {
    id: 'milligram',
    label: 'Миллиграмм',
    shortLabel: 'мг',
    category: 'mass',
    system: 'metric',
    multiplier: 0.000001,
    offset: 0,
  },
  gram: {
    id: 'gram',
    label: 'Грамм',
    shortLabel: 'г',
    category: 'mass',
    system: 'metric',
    multiplier: 0.001,
    offset: 0,
  },
  kilogram: {
    id: 'kilogram',
    label: 'Килограмм',
    shortLabel: 'кг',
    category: 'mass',
    system: 'metric',
    multiplier: 1,
    offset: 0,
  },
  tonne: {
    id: 'tonne',
    label: 'Тонна',
    shortLabel: 'т',
    category: 'mass',
    system: 'metric',
    multiplier: 1000,
    offset: 0,
  },
  ounce: {
    id: 'ounce',
    label: 'Унция',
    shortLabel: 'oz',
    category: 'mass',
    system: 'imperial',
    multiplier: 0.0283495,
    offset: 0,
  },
  pound: {
    id: 'pound',
    label: 'Фунт',
    shortLabel: 'lb',
    category: 'mass',
    system: 'imperial',
    multiplier: 0.453592,
    offset: 0,
  },
  stone: {
    id: 'stone',
    label: 'Стоун',
    shortLabel: 'st',
    category: 'mass',
    system: 'imperial',
    multiplier: 6.35029,
    offset: 0,
  },

  // --- ОБЪЕМ (Базовая единица: литр) ---
  milliliter: {
    id: 'milliliter',
    label: 'Миллилитр',
    shortLabel: 'мл',
    category: 'volume',
    system: 'metric',
    multiplier: 0.001,
    offset: 0,
  },
  liter: {
    id: 'liter',
    label: 'Литр',
    shortLabel: 'л',
    category: 'volume',
    system: 'metric',
    multiplier: 1,
    offset: 0,
  },
  cubic_meter: {
    id: 'cubic_meter',
    label: 'Кубический метр',
    shortLabel: 'м³',
    category: 'volume',
    system: 'metric',
    multiplier: 1000,
    offset: 0,
  },
  cup_us: {
    id: 'cup_us',
    label: 'Чашка (США)',
    shortLabel: 'cup',
    category: 'volume',
    system: 'us_customary',
    multiplier: 0.236588,
    offset: 0,
  },
  pint_us: {
    id: 'pint_us',
    label: 'Пинта (США)',
    shortLabel: 'pt',
    category: 'volume',
    system: 'us_customary',
    multiplier: 0.473176,
    offset: 0,
  },
  quart_us: {
    id: 'quart_us',
    label: 'Кварта (США)',
    shortLabel: 'qt',
    category: 'volume',
    system: 'us_customary',
    multiplier: 0.946353,
    offset: 0,
  },
  gallon_us: {
    id: 'gallon_us',
    label: 'Галлон (США)',
    shortLabel: 'gal',
    category: 'volume',
    system: 'us_customary',
    multiplier: 3.78541,
    offset: 0,
  },
  barrel_oil: {
    id: 'barrel_oil',
    label: 'Баррель нефти',
    shortLabel: 'bbl',
    category: 'volume',
    system: 'us_customary',
    multiplier: 158.987,
    offset: 0,
  },

  // --- ЦИФРОВЫЕ ДАННЫЕ (Базовая единица: байт) ---
  byte: {
    id: 'byte',
    label: 'Байт',
    shortLabel: 'B',
    category: 'digital_data',
    system: 'digital',
    multiplier: 1,
    offset: 0,
  },
  kilobyte: {
    id: 'kilobyte',
    label: 'Килобайт',
    shortLabel: 'KB',
    category: 'digital_data',
    system: 'digital',
    multiplier: 1024,
    offset: 0,
  },
  megabyte: {
    id: 'megabyte',
    label: 'Мегабайт',
    shortLabel: 'MB',
    category: 'digital_data',
    system: 'digital',
    multiplier: 1024 ** 2,
    offset: 0,
  },
  gigabyte: {
    id: 'gigabyte',
    label: 'Гигабайт',
    shortLabel: 'GB',
    category: 'digital_data',
    system: 'digital',
    multiplier: 1024 ** 3,
    offset: 0,
  },
  terabyte: {
    id: 'terabyte',
    label: 'Терабайт',
    shortLabel: 'TB',
    category: 'digital_data',
    system: 'digital',
    multiplier: 1024 ** 4,
    offset: 0,
  },
  petabyte: {
    id: 'petabyte',
    label: 'Петабайт',
    shortLabel: 'PB',
    category: 'digital_data',
    system: 'digital',
    multiplier: 1024 ** 5,
    offset: 0,
  },

  // --- ВРЕМЯ (Базовая единица: секунда) ---
  second: {
    id: 'second',
    label: 'Секунда',
    shortLabel: 'сек',
    category: 'time',
    system: 'scientific',
    multiplier: 1,
    offset: 0,
  },
  minute: {
    id: 'minute',
    label: 'Минута',
    shortLabel: 'мин',
    category: 'time',
    system: 'scientific',
    multiplier: 60,
    offset: 0,
  },
  hour: {
    id: 'hour',
    label: 'Час',
    shortLabel: 'ч',
    category: 'time',
    system: 'scientific',
    multiplier: 3600,
    offset: 0,
  },
  day: {
    id: 'day',
    label: 'День',
    shortLabel: 'дн',
    category: 'time',
    system: 'scientific',
    multiplier: 86400,
    offset: 0,
  },
  week: {
    id: 'week',
    label: 'Неделя',
    shortLabel: 'нед',
    category: 'time',
    system: 'scientific',
    multiplier: 604800,
    offset: 0,
  },
  month: {
    id: 'month',
    label: 'Месяц (средний)',
    shortLabel: 'мес',
    category: 'time',
    system: 'scientific',
    multiplier: 2629746,
    offset: 0,
  },
  year: {
    id: 'year',
    label: 'Год',
    shortLabel: 'г',
    category: 'time',
    system: 'scientific',
    multiplier: 31556952,
    offset: 0,
  },

  // --- ТЕМПЕРАТУРА (Базовая: Цельсий) ---
  celsius: {
    id: 'celsius',
    label: 'Цельсий',
    shortLabel: '°C',
    category: 'temperature',
    system: 'metric',
    multiplier: 1,
    offset: 0,
  },
  fahrenheit: {
    id: 'fahrenheit',
    label: 'Фаренгейт',
    shortLabel: '°F',
    category: 'temperature',
    system: 'imperial',
    multiplier: 5 / 9,
    offset: 32,
  },
  kelvin: {
    id: 'kelvin',
    label: 'Кельвин',
    shortLabel: 'K',
    category: 'temperature',
    system: 'scientific',
    multiplier: 1,
    offset: 273.15,
  },
}

export const UNIT_IDS = Object.keys(UNITS_DATA) as UnitId[]
